[versions]
kotlin = "1.6.21"
coroutines = "1.6.3"

android-gradle = "7.2.1"
androidx-core = "1.8.0"
androidx-lifecycle = "2.5.0"
androidx-activity = "1.5.0"
androidx-navigation = "2.4.2"

compose = "1.2.0-beta03"
material3 = "1.0.0-alpha14"
dagger = "2.42"

room = "2.4.2"
datastore = "1.0.0"

google-services = "4.3.13"
firebase-bom = "30.2.0"
accompanist = "0.24.9-beta"

okhttp = "4.9.3"
retrofit = "2.9.0"
gson = "2.9.0"

junit = "4.13.2"

[libraries]
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android.gradle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }

# Compose
androidx-compose-ui-core = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-compose-ui-tooling-core = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version = "1.0.0" }

google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
google-firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

# Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

# Datastore
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# Network
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Test
junit4 = { module = "junit:junit", version.ref = "junit" }

# Hilt
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "dagger" }
hilt-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "dagger" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }

javax-inject = "javax.inject:javax.inject:1"

[bundles]
compose = ["androidx-compose-ui-core",
    "androidx-compose-ui-tooling-core",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-activity-compose",
    "androidx-compose-navigation",
    "androidx-hilt-navigation-compose"]